### ISSUE TITLE
error when running generate_nircam

### ISSUE THREAD

**Issue by mgennaro** [spacetelescope/pysiaf#112]
I am getting the following error:

```
Apertures with significant roundtrip error differences:
AperName siaf0_metric siaf0_dx_mean siaf0_dy_mean siaf0_dx_rms ... difference_dx_mean difference_dy_mean difference_dx_rms difference_dy_rms
-------- ------------ ------------- ------------- ------------ ... ------------------ ------------------ ----------------- -----------------
Traceback (most recent call last):
  File "generate_nircam.py", line 356, in <module>
    ref_siaf = pysiaf.Siaf(instrument, filename=os.path.join(pre_delivery_dir, 'NIRCam_SIAF_outdated.xml'))
  File "/Users/gennaro/anaconda3/envs/astroconda/lib/python3.5/site-packages/pysiaf-0.5.1-py3.5.egg/pysiaf/siaf.py", line 293, in __init__
    self.apertures = read.read_jwst_siaf(self.instrument, filename=filename, basepath=basepath)
  File "/Users/gennaro/anaconda3/envs/astroconda/lib/python3.5/site-packages/pysiaf-0.5.1-py3.5.egg/pysiaf/iando/read.py", line 400, in read_jwst_siaf
    tree = ET.parse(filename)
  File "src/lxml/lxml.etree.pyx", line 3442, in lxml.etree.parse (src/lxml/lxml.etree.c:81716)
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118635)
  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118982)
  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117894)
  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:112440)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105896)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:107604)
  File "src/lxml/parser.pxi", line 633, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:106415)
OSError: Error reading file '/Users/gennaro/anaconda3/envs/astroconda/lib/python3.5/site-packages/pysiaf-0.5.1-py3.5.egg/pysiaf/pre_delivery_data/NIRCam/NIRCam_SIAF_outdated.xml': failed to load external entity "/Users/gennaro/anaconda3/envs/astroconda/lib/python3.5/site-packages/pysiaf-0.5.1-py3.5.egg/pysiaf/pre_delivery_data/NIRCam/NIRCam_SIAF_outdated.xml"
```

Any recommendations on how to solve it? Looks like a file "NIRCam_SIAF_outdated.xml" is missing.

**Comment by Johannes-Sahlmann** [comment]
I think this can be fixed by replacing in line 354
`for compare_to in [pysiaf.JWST_PRD_VERSION, 'outdated pre-delivery']:`
by 
`for compare_to in [pysiaf.JWST_PRD_VERSION]:`

my apologies for the bug

**Comment by Johannes-Sahlmann** [comment]
resolved.
